---
title: "Project analysis"
author: "Rat Bastards"
output: github_document
---

```{r load-packages, message = FALSE}
 # install.packages("devtools")
 # install.packages("suncalc")  #install these in the console
 # devtools::install_github("datastorm-open/suncalc")
# install.packages("visdat")
# install.packages("naniar")
# install.packages("gganimate")

library(tidyverse)
library(broom)
library(readr)
library(dplyr)
library(forcats)
library(lubridate)
library(devtools)
#library(suncalc)
library(visdat)
library(naniar)                                 
library(gganimate)
```

```{r read-data, message=FALSE, warning=FALSE}
# hurricane_plants <- read_csv("../data/hurricane_plants.csv")

hurricane_plants <- read_csv("../data/hurricane_plants.csv", 
    col_types = cols(date = col_date(format = "%m/%d/%Y")))

weather_data <- read_csv("../data/neracoos_buoy_data.csv")
```

```{r clean-plants-data}
# arrange variables in logical order
hurricane_plants <- relocate(hurricane_plants, 
       date, 
       life_form, 
       species, 
       common_name,
       # angiosperm data
       initial_emergence,
       breaking_leaf_buds_count,
       leaf_presence,
       percent_unfolded_leaves,
       unfolded_leaves_count,
       percent_full_size_leaf,
       percent_leaves_colorful,
       fallen_leaf_presence,
       buds_and_flowers_count,
       percent_open_flowers,
       pollen_amount,
       fruit_count,
       unripe_seed_cone_count, 
       percent_ripe_fruits,
       dropped_fruit_count,
       # pteridophyte data
       percent_stalk_growth,
       percent_fiddlehead_unrolled,
       sporangia_presence,
       releasing_spores,
       # gymnosperm data
       breaking_needle_bud_count,
       young_needle_count,
       percent_open_pollen_cones,
       pollen_cone_count,
       ripe_seed_cone_count,
       
       notes
       )

# remove empty rows, where life_form is NA 
hurricane_plants <- hurricane_plants %>% 
  filter(!is.na(life_form))
```

```{r bar-chart-observations}
hurricane_plants %>%
  ggplot(aes(x = fct_infreq(common_name), fill = life_form)) +
  
  geom_bar() +
  coord_flip() +
  labs(title = "amount of observations by species") +
  xlab("") +
  ylab("") +
  scale_fill_viridis_d()
```

```{r visualize-missing-values}
# show columns with color coded NAs and datatypes
visdat::vis_dat(hurricane_plants)

# create lolipop graph of NAs by column
naniar::gg_miss_var(hurricane_plants)

gg_miss_fct(hurricane_plants, fct = common_name)
```

```{r find-initial-emergence}
# first emergence column creation
hurricane_plants_join <- hurricane_plants %>%
  # mutate(date = as.Date(date)) %>%
  group_by(species, initial_emergence) %>% 
  filter(date == min(date)) %>% 
  slice(1) %>% # takes the first occurrence if there is a tie
  ungroup() %>%
  filter(initial_emergence == "TRUE") %>%
  dplyr::select(date, species, first_emergence=initial_emergence)

hurricane_plants <- hurricane_plants %>%
  full_join(hurricane_plants_join, join_by(date, species))
```

```{r calculate-phenophases}
# create leafing out phenophase
hurricane_plants <- hurricane_plants %>%
  mutate(leaf_out = case_when(
    initial_emergence == T & 
      buds_and_flowers_count == 0 & 
      common_name %in% c("yarrow", 
                         "water lily", 
                         "mustard", 
                         "foxglove", 
                         "Canada mayflower", 
                         "calendula", 
                         "bull thistle", 
                         "beach pea") ~ T,
    breaking_leaf_buds_count > 0 &
      percent_full_size_leaf < 1 &
      common_name %in% c("bayberry", 
                         "horse chestnut", 
                         "raspberry", 
                         "red elderberry") ~ T,
    breaking_leaf_buds_count > 0 &
      percent_unfolded_leaves < 1 &
      common_name %in% c("blueberry", 
                         "American black elderberry", 
                         "blackberry", 
                         "beach rose",
                         "apple") ~ T,
    initial_emergence == T &
      percent_unfolded_leaves < 1 &
      common_name %in% c("peony") ~ T,
    unfolded_leaves_count > 0 &
      percent_full_size_leaf < 1 &
      common_name %in% c("garlic") ~ T,
    initial_emergence == T &
      percent_fiddlehead_unrolled < 1 &
      common_name %in% c("cinnamon fern") ~ T,
    .default = F
  ))
  
# create budding phenophase
hurricane_plants <- hurricane_plants %>%
  mutate(budding = case_when(
    buds_and_flowers_count > 0 & 
      percent_open_flowers < 1 & 
      common_name %in% c("yarrow", 
                         "water lily",
                         "starflower",
                         "red elderberry",
                         "raspberry",
                         "peony",
                         "mustard",
                         "horse chestnut",
                         "foxglove", 
                         "Canada mayflower", 
                         "calendula", 
                         "American black elderberry", 
                         "blackberry", 
                         "beach rose",
                         "beach pea",
                         "bayberry",
                         "apple") ~ T,
    buds_and_flowers_count > 0 &
      date < 7/25/2023 &
      common_name %in% c("bull thistle") ~ T,
    buds_and_flowers_count > 0 &
      date < 6/13/2023 &
      common_name %in% c("blueberry") ~ T,
    sporangia_presence == T &
      releasing_spores == F &
      common_name %in% c("cinnamon fern") ~ T,
    .default = F
  ))

# create flowering phenophase
hurricane_plants <- hurricane_plants %>%
  mutate(flowering = case_when(
    percent_open_flowers > 0 & 
      buds_and_flowers_count > 0 &
      #buds_and_flowers_count != NA & 
      common_name %in% c("yarrow",
                         "starflower",
                         "red elderberry",
                         "peony",
                         "mustard",
                         "horse chestnut",
                         "foxglove", 
                         "Canada mayflower", 
                         "bull thistle",
                         "blueberry",
                         "American black elderberry", 
                         "blackberry", 
                         "beach rose",
                         "beach pea",
                         "bayberry",
                         "apple") ~ T,
    buds_and_flowers_count == NA ~ F,
    percent_open_flowers > 0 &
      common_name %in% c("water lily", "calendula") ~ T,
    percent_open_flowers > 0 &
      buds_and_flowers_count != 0 &
      common_name %in% c("raspberry") ~ T,
    .default = F
  ))

# create fruiting phenophase
hurricane_plants <- hurricane_plants %>%
  mutate(fruiting = case_when(
    percent_ripe_fruits > 0 &
      # fruit_count != NA &
      common_name %in% c("yarrow",
                         "raspberry",
                         "peony",
                         "mustard",
                         "horse chestnut",
                         "foxglove", 
                         "Canada mayflower", 
                         "bull thistle",
                         "blueberry",
                         "American black elderberry", 
                         "blackberry", 
                         "beach rose",
                         "beach pea",
                         "apple") ~ T,

    ripe_seed_cone_count > 0 &
      common_name %in% c("red spruce") ~ T,
    
    fruit_count > 0 &
      dropped_fruit_count < 10000 &
      common_name %in% c("red elderberry") ~ T,
    .default = F
  ))

# create dispersal phenophase
hurricane_plants <- hurricane_plants %>%
  mutate(dispersal = case_when(
    dropped_fruit_count > 0 &
      fruit_count > 0 &
      common_name %in% c("red elderberry",
                         "raspberry",
                         "mustard",
                         "horse chestnut",
                         "foxglove", 
                         "Canada mayflower", 
                         "calendula",
                         "bull thistle",
                         "blueberry",
                         "American black elderberry", 
                         "blackberry", 
                         "beach rose",
                         "beach pea",
                         "apple") ~ T,

    dropped_fruit_count > 0 &
      common_name %in% c("yarrow", "starflower", "peony") ~ T,
    
    releasing_spores == T &
      common_name %in% c("cinnamon fern") ~ T,
    .default = F
  ))

# pivot longer
hurricane_plants_long <- hurricane_plants %>%
  pivot_longer(
    cols = c(leaf_out : dispersal), 
    names_to = "phenophase"
  ) %>%
  filter(value == "TRUE") %>%
  group_by(species, common_name, life_form, phenophase) %>%
  summarize(start_date = min(date), 
            end_date = max(date))

# reformat phenophase labels
hurricane_plants_long <- hurricane_plants_long %>%
  mutate(phenophase = case_when(
    phenophase == "leaf_out"           ~ "leafing out",
    phenophase == "dispersal"          ~ "dispersing",
    TRUE                                           ~ phenophase
  ))
```

```{r lolipop-phenophases-by-phase, warning=FALSE}
hurricane_plants_long %>%
  # filter(phenophase == "leafing out") %>%
ggplot() +
  geom_segment(aes(x = fct_reorder(common_name, life_form),
                    y = start_date, 
                    xend = fct_reorder(common_name, life_form),
                 yend = end_date,
                 color = life_form)) +
  #geom_line(y = min(date)) +
  coord_flip()+
 facet_wrap(~ fct_relevel(phenophase, c("dispersing",
                                        "fruiting",
                                        "flowering",
                                        "budding",
                                        "leafing out")),
            scales = "free_y",
            ncol = 1, strip.position = "left") +
  theme_minimal() +
  theme(legend.position = "bottom",) +
  labs(x = "",
       y = "date range",
       title = "phenophase date ranges by species",
       color = "life form") +
  scale_color_viridis_d()

# ggsave("phenophase_timings.png")
```

```{r singular-phase-plots}
# just leafing out
hurricane_plants_long %>%
   filter(phenophase == "leafing out") %>%
   drop_na(start_date) %>%
ggplot() +
  geom_segment(aes(x = fct_reorder(species, as.numeric(start_date)),
                    y = start_date, 
                    xend = fct_reorder(species, as.numeric(start_date)),
                 yend = end_date,
                  color = life_form)) +

  geom_point(aes(x = fct_reorder(species, start_date),
                 y = start_date),
             color = "aquamarine3",
             size = 1 ) +

  geom_point(aes(x = fct_reorder(species, start_date),
                 y = end_date),
             color = "firebrick3",
             size = 1 ) +
  #geom_line(y = min(date)) +
  coord_flip()+
  theme_minimal() +
  theme(legend.position = "bottom",) +
  labs(x = "phenophase",
       y = "date range",
       title = "leafing out timing",
       color = "life form") +
  scale_color_viridis_d()



# just budding
hurricane_plants_long %>%
   filter(phenophase == "budding") %>%
   drop_na(start_date) %>%
ggplot() +
  geom_segment(aes(x = fct_reorder(species, as.numeric(start_date)),
                    y = start_date, 
                    xend = fct_reorder(species, as.numeric(start_date)),
                 yend = end_date,
                  color = life_form)) +

  geom_point(aes(x = fct_reorder(species, start_date),
                 y = start_date),
             color = "aquamarine3",
             size = 1 ) +

  geom_point(aes(x = fct_reorder(species, start_date),
                 y = end_date),
             color = "firebrick3",
             size = 1 ) +
  #geom_line(y = min(date)) +
  coord_flip()+
  theme_minimal() +
  theme(legend.position = "bottom",) +
  labs(x = "phenophase",
       y = "date range",
       title = "budding timing",
       color = "life form") +
  scale_color_viridis_d()



# just flowering
hurricane_plants_long %>%
   filter(phenophase == "flowering") %>%
   drop_na(start_date) %>%
ggplot() +
  geom_segment(aes(x = fct_reorder(species, as.numeric(start_date)),
                    y = start_date, 
                    xend = fct_reorder(species, as.numeric(start_date)),
                 yend = end_date,
                  color = life_form)) +

  geom_point(aes(x = fct_reorder(species, start_date),
                 y = start_date),
             color = "aquamarine3",
             size = 1 ) +

  geom_point(aes(x = fct_reorder(species, start_date),
                 y = end_date),
             color = "firebrick3",
             size = 1 ) +
  #geom_line(y = min(date)) +
  coord_flip()+
  theme_minimal() +
  theme(legend.position = "bottom",) +
  labs(x = "phenophase",
       y = "date range",
       title = "flowering timing",
       color = "life form") +
  scale_color_viridis_d()



# just fruiting
hurricane_plants_long %>%
   filter(phenophase == "fruiting") %>%
   drop_na(start_date) %>%
ggplot() +
  geom_segment(aes(x = fct_reorder(species, as.numeric(start_date)),
                    y = start_date, 
                    xend = fct_reorder(species, as.numeric(start_date)),
                 yend = end_date,
                  color = life_form)) +

  geom_point(aes(x = fct_reorder(species, start_date),
                 y = start_date),
             color = "aquamarine3",
             size = 1 ) +

  geom_point(aes(x = fct_reorder(species, start_date),
                 y = end_date),
             color = "firebrick3",
             size = 1 ) +
  #geom_line(y = min(date)) +
  coord_flip()+
  theme_minimal() +
  theme(legend.position = "bottom",) +
  labs(x = "phenophase",
       y = "date range",
       title = "fruiting timing",
       color = "life form") +
  scale_color_viridis_d()



# just dispersing
hurricane_plants_long %>%
   filter(phenophase == "dispersing") %>%
   drop_na(start_date) %>%
ggplot() +
  geom_segment(aes(x = fct_reorder(species, as.numeric(start_date)),
                    y = start_date, 
                    xend = fct_reorder(species, as.numeric(start_date)),
                 yend = end_date,
                  color = life_form)) +

  geom_point(aes(x = fct_reorder(species, start_date),
                 y = start_date),
             color = "aquamarine3",
             size = 1 ) +

  geom_point(aes(x = fct_reorder(species, start_date),
                 y = end_date),
             color = "firebrick3",
             size = 1 ) +
  #geom_line(y = min(date)) +
  coord_flip()+
  theme_minimal() +
  theme(legend.position = "bottom",) +
  labs(x = "phenophase",
       y = "date range",
       title = "dispersing timing",
       color = "life form") +
  scale_color_viridis_d()
```

```{r categories-attempt}
# create column with woody/herbaceous/fern/coniferous
hurricane_plants_categorized <- hurricane_plants %>%
  mutate(plant_type = case_when(
    common_name == "bull thistle" ~ "herbaceous",
    common_name == "cinnamon fern" ~ "fern",
    common_name == "red spruce" ~ "coniferous",
    life_form == "vine" ~ "herbaceous",
    life_form == "shrub" ~ "woody",
    life_form == "tree" ~ "woody",
    life_form == "herb" ~ "herbaceous",
    life_form == "vine" ~ "herbaceous",
    .default = "Other"
  ))
```

```{r faceted-lolipop-plot, warning=FALSE}
hurricane_plants_long %>%
 #filter(species == "Achillea millefolium") %>%
ggplot() +
  geom_segment( aes(x = (fct_relevel(phenophase, c("leafing out",
                                        "budding",
                                        "flowering",
                                        "fruiting",
                                        "dispersing"))), 
                    xend = (fct_relevel(phenophase, c("leafing out",
                                        "budding",
                                        "flowering",
                                        "fruiting",
                                        "dispersing"))),
                    y = start_date, 
                    yend=end_date), 
                color = "grey") +
  
  geom_point(aes(x = (fct_relevel(phenophase, c("leafing out",
                                        "budding",
                                        "flowering",
                                        "fruiting",
                                        "dispersing"))),
                 y = start_date), 
             color = "aquamarine3", 
             size = 1 ) +
  
  geom_point(aes(x = (fct_relevel(phenophase, c("leafing out",
                                        "budding",
                                        "flowering",
                                        "fruiting",
                                        "dispersing"))),
                 y = end_date), 
             color = "firebrick3", 
             size = 1 ) +
  #geom_line(y = min(date)) +
  coord_flip()+
  facet_wrap(~ species) +
  theme_minimal() +
  theme(legend.position = "none",) +
  labs( x = "phenophase",
    #x = "",
       y = "date range",
       title = "phenophase date ranges")
```

```{r overall-count-for-apple}
#do breaking leaf buds, buds and flowers, fruit count, dropped fruit count. Just for apple, do it as line

hurricane_plants %>%
  filter(species %in% c("Malus sp.")) %>%
  ggplot(aes(x = date)) +
  geom_line(aes(y = breaking_leaf_buds_count, color = "green")) +
  geom_line(aes(y = buds_and_flowers_count, color = "pink"))+
  geom_line(aes(y = fruit_count, color = "blue"))+
  geom_line(aes(y = dropped_fruit_count, color = "orange"))
#ask laurie how to make this good and normal
```

```{r berry-comparisons}
#comparisons with raspberry, blackberry, and blueberry

hurricane_plants %>%
  filter(species %in% c("Rubus allegheniensis", "Vaccinium angustifolium", "Rubus idaeus")) %>%
  filter(!is.na(percent_ripe_fruits)) %>%
  ggplot(aes(x = date, y = percent_ripe_fruits, color = species)) +
  geom_line() +
  labs(title = "Percent ripe fruit coverage over time",
       subtitle = "Coverage in three fruit-bearing individuals in the 2023 season",
       x = "Month",
       y = "Percent of ripe fruit",
       color = "Species") +
  scale_color_viridis_d()

#Fruit numbers throughout the season
hurricane_plants %>%
  filter(species %in% c("Rubus allegheniensis", "Vaccinium angustifolium", "Rubus idaeus")) %>%
  ggplot(aes(x = date, y = fruit_count, color = species)) +
  geom_line() +
  labs(title = "Fruit count over time",
       subtitle = "Total visible fruits on three individuals in the 2023 season",
       x = "Month",
       y = "Fruit count",
       color = "Species") +
  scale_color_viridis_d()
#note that the blackberry bush was apparently huge so would have way more fruits than the other two
```

```{r lolipop-animation}
my_anim <- hurricane_plants_long %>%
ggplot(aes(group = species)) +
  geom_segment( aes(x = (fct_relevel(phenophase, c("leaf_out",
                                                   "budding",
                                                   "flowering",
                                                   "fruiting",
                                                   "dispersal"))), 
                    xend = (fct_relevel(phenophase, c("leaf_out",
                                                      "budding",
                                                      "flowering",
                                                      "fruiting",
                                                      "dispersal"))),
                    y = start_date, 
                    yend=end_date), 
                color = "grey") +
  
  geom_point(aes(x = (fct_relevel(phenophase, c("leaf_out", 
                                                "budding", 
                                                "flowering", 
                                                "fruiting",
                                                "dispersal"))),
                 y = start_date), 
             color = "aquamarine3", 
             size = 1 ) +
  
  
  geom_point(aes(x = (fct_relevel(phenophase, c("leaf_out", 
                                                "budding", 
                                                "flowering", 
                                                "fruiting",
                                                "dispersal"))),
                 y = end_date), 
             color = "firebrick3", 
             size = 1 ) +
  coord_flip() +
  theme_minimal() +
  theme(legend.position = "none",) +
  labs(x = "phenophase",
       y = "date range",
       title = "phenophase date ranges by species") +
  transition_states(states = species)
library(gifski)
animate(my_anim, duration = 20, fps = 20, width = 200, height = 200, renderer = gifski_renderer())

anim_save(filename = "lollipop.gif")
```

```{r weather-initial-analysis, warning=FALSE}
# lubridate weather entries, calculate useful daily temperatures
weather_data <- weather_data %>%
  mutate(time = ymd_hms(time),
         month = month(time),
         day = day(time),
         date = as_date(round_date(time, unit = "day"))) %>%
  mutate(air_temperature = as.numeric(air_temperature)) %>%
  group_by(date) %>%
  summarize(daily_mean_temp = mean(air_temperature, na.rm = TRUE),
            daily_min_temp = min(air_temperature, na.rm = TRUE),
            daily_max_temp = max(air_temperature, na.rm = TRUE),
            daily_sd_temp = sd(air_temperature, na.rm = TRUE))

# glimpse weather data
glimpse(weather_data)
```

```{r species-temperature-specifications}
# set species minimums for temperatures and calculate total days above "frosts"
weather_data %>%
  group_by(date) %>%
  mutate(yarrow_temp_above = case_when(daily_mean_temp > 5 ~ 1, 
                                       TRUE ~ 0),
         apple_temp_above = case_when(daily_mean_temp > 12 ~ 1, 
                                       TRUE ~ 0)) %>% #find relevant temperatures, name by species, and join to hurricane_plants by this variable (dates after critical period)
  pivot_longer(cols = c(yarrow_temp_above, apple_temp_above), names_to = "species_germ", values_to = "germination_possible") %>%
  filter(germination_possible == 1) %>% #earliest non-frost or favourable germination date
  group_by(species_germ) %>%
  slice_min(date, n = 1)
```

```{r daily-mean-temp}
# line plot daily mean temperature
ggplot(weather_data, aes(x=date, y=daily_mean_temp)) +
  geom_line() 
```

```{r plot-temperature-ranges}
# plot ribbon of daily temperature readings
weather_data %>%
  ggplot(aes(x = date)) +
    geom_ribbon(aes(y = daily_mean_temp, ymin = daily_min_temp, ymax = daily_max_temp), alpha = 0.3) +
    # geom_line(aes(y = daily_mean_temp), color = "blue") +
    geom_line(aes(y = daily_min_temp), color = "skyblue") +
    geom_line(aes(y = daily_max_temp), color = "violetred3")
```

```{r hurricane-points-and-zones, message=FALSE}
# read points
plant_points <- read_csv("../data/hurricane_points.csv")
plant_zones <- read_csv("../data/hurricane_zones.csv")
points_and_zones <-read_csv("../data/plantsandzones.csv")

#join plant points and points and zones
map_join <- plant_points %>%
  left_join(points_and_zones, by = "Plant")

library(leaflet) ## For leaflet interactive maps
#assign colors to zones for map
zone_color <- colorFactor(palette = c("#a6cee3", "#1f78b4", "#b2df8a", "#33a02c", "#fb9a99"),
                          domain = c("Ice Pond", "Main Campus", "Main Garden Area", "Meadow Garden", "South End & High Cliffs"),
                          ordered = TRUE)
```

```{r hurricane-leaflet}
# #install.packages(leaflet)
library(leaflet) ## For leaflet interactive maps
library(sf) ## For spatial data
# library(htmltools) ## For html
# library(leafsync) ## For placing plots side by side
# library(kableExtra) ## Table output
# library(stringr) ## String manipulation
# install.packages("remotes")
# remotes::install_gitlab("dickoa/rgeoboundaries")
# library(rgeoboundaries) ## Administrative boundaries
# install.packages()
# library(sp)

library(htmltools) ## For html
library(leafsync) ## For placing plots side by side
library(kableExtra) ## Table output
library(stringr) ## String manipulation
#install.packages("remotes")
#remotes::install_gitlab("dickoa/rgeoboundaries")
library(rgeoboundaries) ## Administrative boundaries
#install.packages()
library(sp)
# install.packages("rgdal")
# library(rgdal)


# create map
leaflet(data = map_join) %>%
   addTiles() %>%
  addProviderTiles(providers$OpenStreetMap) %>%
   setView(lng = -68.895, #<<
           lat = 44.0348, #<<
           zoom = 14.45) %>% #<<
  addCircles(~x, ~y,
          fillColor = ~zone_color(map_join$Zone),
             weight = 1,
             color = "black",
             fillOpacity = 0.7,
             radius = 10,
          highlight = highlightOptions(
            weight = 3,
            color = "blue",
            fillOpacity = 1,
            bringToFront = TRUE
          ),
          label = ~Plant) %>%
  addLegend(
    position = "bottomright",
    pal = zone_color,
    values = ~map_join$Zone,
    title = "Plant Locations by Zone",
    opacity = 1
  )
```



